logging:
  debug: false
  level: INFO
  log_dir: logs/live_trading

paths:
  logs: logs/live_trading

environment:
  instruments: ["XAUUSD"]
  timeframes: ["M15", "H1", "H4", "D1"]
  num_envs: 1
  data_source: "live"
  max_steps: 50
  enable_shadow_sim: false

mode:
  name: "live"
  training: false
  live: true
  enable_shadow_sim: false

rl:
  final_training_steps: 0
  log_interval: 1
  checkpoint_freq: 0
  eval_freq: 0

# mt5:
#   account: 1512227067
#   password: "@j853U*BunDEl1"
#   server: "FTMO-Demo"
#   # Path to FTMO MT5 terminal executable (required when multiple MT5 installations exist)
#   path: "C:\\Program Files\\FTMO Global Markets MT5 Terminal\\terminal64.exe"

mt5:
  account: 5044985957
  password: "U@0uSlXa"
  server: "MetaQuotes-Demo"
  # Path to FTMO MT5 terminal executable (required when multiple MT5 installations exist)
  path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"

risk_overrides:
  emergency_drawdown_trigger: 0.09
