# envs/exploration_env.py
"""
Lightweight Exploration Environment for Autonomous PPO Training
===============================================================

This environment supports two modes:

1) INLINE (standalone) mode:
   - No SmartInfoBus / Orchestrator dependency
   - Computes a lightweight approximation of the 64-dim observation vector

2) PREBAKED (module-observation) mode:
   - Loads the exact 64-dim observation vector produced by your module pipeline
     (generated by scripts/prebake_signals.py)
   - Overrides ONLY the account-dependent slots live each step
   - Training runs much faster because modules are NOT executed during training
   - Integrates training-only rule adapters, prop constraints, and safety filters

Critical invariants:
- Observation layout MUST match training.contracts.obs_contract.OBS_COLUMNS exactly.
- Uses simulation time from prebaked data, NEVER wall-clock time.
- Naive datetimes are treated as Europe/Berlin local time (NOT UTC).
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces

warnings.filterwarnings("ignore", category=RuntimeWarning)

# ──────────────────────────────────────────────────────────────────────────────
# Training-only imports (optional)
# ──────────────────────────────────────────────────────────────────────────────
_HAS_TRAINING_RULES = False
_RuleAdapterClass = None
_PropConstraintsClass = None
_SafetyFilterClass = None
_load_all_prebaked_func = None
_PrebakedDatasetClass = None

CONTRACT_OBS_COLUMNS = None
CONTRACT_OBS_IDX = None
schema_hash = None

try:
    from training.contracts.obs_contract import (
        OBS_COLUMNS as CONTRACT_OBS_COLUMNS,
        OBS_IDX as CONTRACT_OBS_IDX,
        schema_hash,
    )
    from training.datasets.prebaked_dataset import PrebakedDataset, load_all_prebaked
    from training.rules.rule_adapter import RuleAdapter
    from training.rules.prop_constraints import PropConstraints
    from training.rules.safety_filter import SafetyFilter

    _HAS_TRAINING_RULES = True
    _RuleAdapterClass = RuleAdapter
    _PropConstraintsClass = PropConstraints
    _SafetyFilterClass = SafetyFilter
    _load_all_prebaked_func = load_all_prebaked
    _PrebakedDatasetClass = PrebakedDataset
except ImportError:
    PrebakedDataset = None
    RuleAdapter = None
    PropConstraints = None
    SafetyFilter = None

# ──────────────────────────────────────────────────────────────────────────────
# Canonical observation schema (prefer contract to avoid drift)
# ──────────────────────────────────────────────────────────────────────────────
if CONTRACT_OBS_COLUMNS is not None and CONTRACT_OBS_IDX is not None:
    OBS_COLUMNS: List[str] = list(CONTRACT_OBS_COLUMNS)
    OBS_IDX: Dict[str, int] = dict(CONTRACT_OBS_IDX)
else:
    # Fallback (only used if training contracts cannot be imported)
    OBS_COLUMNS = [
        # M15 Price Features [0-9]
        "m15_price_norm", "m15_return_1", "m15_return_5", "m15_return_20",
        "m15_volatility", "m15_rsi", "m15_atr_norm", "m15_trend_strength",
        "m15_momentum", "m15_volume_ratio",
        # HTF Context [10-15]
        "htf_h1_trend", "htf_h4_trend", "htf_d1_trend",
        "htf_alignment", "htf_volatility_ratio", "htf_context_strength",
        # Voting/Expert Signals [16-23]
        "expert_theme_signal", "expert_trend_signal", "expert_momentum_signal",
        "expert_seasonality_signal", "expert_5", "expert_6", "expert_7", "expert_8",
        # Committee Consensus [24-31]
        "consensus_direction", "consensus_confidence", "consensus_agreement",
        "committee_bullish_count", "committee_bearish_count", "committee_neutral_count",
        "committee_strength", "committee_clarity",
        # Risk/Memory [32-39]
        "risk_level", "risk_gate", "memory_gate", "danger_zone_count",
        "recent_loss_streak", "drawdown_risk", "exposure_risk", "risk_adjusted_size",
        # Account State [40-47]
        "balance_norm", "equity_norm", "margin_used", "drawdown_pct",
        "position_count", "position_exposure", "daily_pnl_norm", "win_rate",
        # World Model Predictions [48-55]
        "wm_price_pred", "wm_volatility_pred", "wm_trend_pred", "wm_confidence",
        "wm_scenario_bull", "wm_scenario_bear", "wm_scenario_range", "wm_uncertainty",
        # Trading Mode [56-63]
        "mode_intensity", "mode_entry_allowed", "mode_entry_quality", "mode_risk_mult",
        "timing_score", "session_quality", "liquidity_score", "mode_effectiveness",
    ]
    OBS_IDX = {k: i for i, k in enumerate(OBS_COLUMNS)}

assert len(OBS_COLUMNS) == 64, f"Expected 64 columns, got {len(OBS_COLUMNS)}"

# Use stdlib ZoneInfo when available (Python 3.9+)
try:
    from zoneinfo import ZoneInfo
    _BERLIN_TZ = ZoneInfo("Europe/Berlin")
except Exception:
    _BERLIN_TZ = None


# ─────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────
@dataclass
class ExplorationConfig:
    """Configuration for exploration training environment."""

    # Account
    initial_balance: float = 100_000.0

    # Trading
    instruments: List[str] = field(default_factory=lambda: ["EURUSD", "XAUUSD"])
    primary_timeframe: str = "M15"

    # Position sizing
    base_lot_size: float = 0.1
    max_lot_size: float = 1.0

    # Risk Management (simplified)
    take_profit_eur: float = 500.0
    stop_loss_eur: float = 200.0
    max_position_age: int = 100
    max_drawdown_pct: float = 0.20

    # PPO hyperparameters
    gamma: float = 0.95
    learning_rate: float = 3e-4

    # Direction thresholds
    direction_long_threshold: float = 0.3
    direction_short_threshold: float = -0.3

    # Environment
    max_steps_per_episode: int = 2000
    observation_size: int = 64

    # Data
    data_dir: str = "data/processed"

    # Prebaked signals
    use_prebaked_signals: bool = False
    prebaked_dir: str = "data/prebaked"

    # Training-only: Enable rule-based constraints
    enable_training_rules: bool = True
    enable_session_filter: bool = True
    enable_prop_constraints: bool = True
    enable_safety_filter: bool = True
    enable_gate_checks: bool = True
    strict_prop_mode: bool = False  # Terminate on prop violations


# ─────────────────────────────────────────────────────────────────
# Position tracking
# ─────────────────────────────────────────────────────────────────
@dataclass
class Position:
    instrument: str
    direction: str          # "long" or "short"
    entry_price: float
    entry_step: int         # episode_step at entry (decision time)
    lot_size: float
    peak_pnl: float = 0.0


# ─────────────────────────────────────────────────────────────────
# Exploration Environment
# ─────────────────────────────────────────────────────────────────
class ExplorationTradingEnv(gym.Env):
    """
    Lightweight trading environment for PPO exploration.

    In prebaked mode:
    - obs = prebaked_signals[step] (fast)
    - account slots [40..47] are overwritten live
    - reward shaping reads signals using canonical OBS_IDX mapping

    Important correctness fix:
    - step(action) applies action at CURRENT bar (current_step), then advances to next bar.
      This avoids look-ahead bias.
    """

    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        data_dict: Optional[Dict[str, Dict[str, pd.DataFrame]]] = None,
        config: Optional[ExplorationConfig] = None,
    ):
        super().__init__()

        self.config = config or ExplorationConfig()
        self.data = data_dict

        # Prebaked signals and datasets - loaded early for instrument validation
        self._prebaked_signals: Dict[str, np.ndarray] = {}
        self._prebaked_datasets: Dict[str, Any] = {}      # PrebakedDataset instances
        self._prebaked_datetimes: Dict[str, np.ndarray] = {}  # int64 ns arrays

        if self.config.use_prebaked_signals:
            self._load_prebaked_signals()

        # Validate instruments
        if data_dict is not None:
            self.instruments = [inst for inst in self.config.instruments if inst in data_dict]
            if not self.instruments:
                self.instruments = list(data_dict.keys())[:2]
        elif self._prebaked_signals:
            self.instruments = list(self._prebaked_signals.keys())
            if not self.instruments:
                self.instruments = self.config.instruments[:2]
        else:
            self.instruments = self.config.instruments[:2]

        if not self.instruments:
            raise ValueError("No valid instruments found in data or prebaked signals")

        # Action space: [direction_score, size_score] per instrument
        n_instruments = len(self.instruments)
        self.action_space = spaces.Box(
            low=-1.0,
            high=1.0,
            shape=(n_instruments * 2,),
            dtype=np.float32,
        )

        # Observation space: 64 dims
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.config.observation_size,),
            dtype=np.float32,
        )

        # State (account + episode)
        self.balance = self.config.initial_balance
        self.initial_balance = self.config.initial_balance

        self.current_step = 0          # index in price/signal arrays
        self.episode_step = 0          # step counter within episode (decision count)

        self.positions: Dict[str, Position] = {}
        self.total_pnl = 0.0
        self.trade_count = 0
        self.win_count = 0

        # Equity-based tracking (more realistic than balance-only)
        self.equity = self.config.initial_balance
        self.peak_equity = self.config.initial_balance

        # Day/session tracking (simulation time, Europe/Berlin local semantics)
        self._day_key: int = 0
        self._daily_pnl = 0.0
        self._day_start_balance = self.config.initial_balance

        self._session_key: int = -1           # YYYYMMDD for active session; -1 for not-in-session
        self._trades_in_session: int = 0

        # Anti-overfit: action diversity tracking
        self._episode_actions: List[float] = []

        # Metrics for callback
        self.total_trades = 0
        self.winning_trades = 0

        # Instrument used for observation
        self._obs_instrument: str = self.instruments[0]

        # Training-only components
        self._rule_adapter: Optional[Any] = None
        self._prop_constraints: Optional[Any] = None
        self._safety_filter: Optional[Any] = None

        # Initialize training rules if enabled
        if _HAS_TRAINING_RULES and self.config.enable_training_rules:
            self._init_training_rules()

        # Data info
        self._min_data_len = self._get_min_data_length()

    # ──────────────────────────────────────────────────────────────
    # Time helpers
    # ──────────────────────────────────────────────────────────────
    def _ensure_berlin_aware(self, dt: datetime) -> datetime:
        """
        Ensure dt is Europe/Berlin tz-aware.
        Naive datetimes are interpreted as already-local Berlin time (not UTC).
        """
        if _BERLIN_TZ is None:
            return dt
        if dt.tzinfo is None:
            return dt.replace(tzinfo=_BERLIN_TZ)
        try:
            return dt.astimezone(_BERLIN_TZ)
        except Exception:
            return dt

    @staticmethod
    def _dt_to_day_key(dt: datetime) -> int:
        return dt.year * 10000 + dt.month * 100 + dt.day

    # ──────────────────────────────────────────────────────────────
    # Training rules initialization
    # ──────────────────────────────────────────────────────────────
    def _init_training_rules(self) -> None:
        """Initialize training-only rule adapters and constraints."""
        if not _HAS_TRAINING_RULES:
            return
        if _RuleAdapterClass is None or _PropConstraintsClass is None or _SafetyFilterClass is None:
            return

        try:
            self._rule_adapter = _RuleAdapterClass(mode="training")

            # Prop constraints
            if self.config.enable_prop_constraints:
                self._prop_constraints = _PropConstraintsClass.from_rule_adapter(self._rule_adapter)

                # Best-effort: wire position_manager.max_consecutive_losses if present in risk_policy
                try:
                    rp = getattr(self._rule_adapter, "_risk_policy", {}) or {}
                    pm = rp.get("position_manager", {}) or {}
                    mcl = pm.get("max_consecutive_losses", None)
                    if mcl is not None:
                        self._prop_constraints.max_consecutive_losses = int(mcl)
                except Exception:
                    pass

            # Safety filter
            if self.config.enable_safety_filter and self._prop_constraints is not None:
                self._safety_filter = _SafetyFilterClass(
                    rule_adapter=self._rule_adapter,
                    prop_constraints=self._prop_constraints,
                    direction_long_threshold=self.config.direction_long_threshold,
                    direction_short_threshold=self.config.direction_short_threshold,
                    enable_gate_checks=self.config.enable_gate_checks,
                    enable_quality_check=True,
                    strict_mode=self.config.strict_prop_mode,
                )

            print("[TRAINING] Initialized training rules:")
            print(f"  - RuleAdapter: {self._rule_adapter is not None}")
            print(f"  - PropConstraints: {self._prop_constraints is not None}")
            print(f"  - SafetyFilter: {self._safety_filter is not None}")

        except Exception as e:
            warnings.warn(f"Failed to initialize training rules: {e}")
            self._rule_adapter = None
            self._prop_constraints = None
            self._safety_filter = None

    # ──────────────────────────────────────────────────────────────
    # Prebaked loading
    # ──────────────────────────────────────────────────────────────
    def _load_prebaked_signals(self) -> None:
        """Load pre-baked module observations from CSV/NPZ in canonical order."""
        from pathlib import Path

        prebaked_dir = Path(self.config.prebaked_dir)
        tf = self.config.primary_timeframe
        load_instruments = self.config.instruments

        # Prefer PrebakedDataset (cache-aware)
        if _HAS_TRAINING_RULES and _load_all_prebaked_func is not None:
            try:
                datasets = _load_all_prebaked_func(
                    prebaked_dir=prebaked_dir,
                    instruments=load_instruments,
                    timeframe=tf,
                )

                for inst, ds in datasets.items():
                    # Hard guard: schema drift
                    if schema_hash is not None:
                        ds_hash = (ds.meta or {}).get("schema_hash", None)
                        if ds_hash is not None and ds_hash != schema_hash():
                            raise ValueError(
                                f"Schema hash mismatch for {inst}: expected {schema_hash()}, got {ds_hash}. "
                                f"Re-run prebake_signals.py."
                            )

                    self._prebaked_datasets[inst] = ds
                    self._prebaked_signals[inst] = ds.obs
                    self._prebaked_datetimes[inst] = ds.dt
                    print(f"[PREBAKED] Loaded {len(ds)} signals for {inst} (schema: {ds.schema_version})")

                if self._prebaked_datasets:
                    return
            except Exception as e:
                warnings.warn(f"PrebakedDataset loading failed, falling back to CSV: {e}")

        # Fallback: direct CSV loading
        for inst in load_instruments:
            signal_file = prebaked_dir / f"{inst}_{tf}_signals.csv"
            if not signal_file.exists():
                print(f"[PREBAKED] Warning: Signal file not found: {signal_file}")
                continue

            df = pd.read_csv(signal_file)

            missing = [c for c in OBS_COLUMNS if c not in df.columns]
            if missing:
                print(f"[PREBAKED] Warning: {signal_file} missing columns ({len(missing)}). Example: {missing[:5]}")
                continue

            arr = df[OBS_COLUMNS].to_numpy(dtype=np.float32, copy=True)
            if arr.ndim != 2 or arr.shape[1] != 64:
                print(f"[PREBAKED] Warning: {signal_file} shape {arr.shape}, expected (N, 64)")
                continue

            self._prebaked_signals[inst] = arr

            # Parse datetime for simulation time (tz-aware -> Berlin -> naive)
            dt_col = None
            for col in ["datetime", "timestamp", "time", "date"]:
                if col in df.columns:
                    dt_col = col
                    break

            if dt_col:
                dt = pd.to_datetime(df[dt_col], errors="coerce")
                try:
                    if getattr(dt.dt, "tz", None) is not None:
                        dt = dt.dt.tz_convert("Europe/Berlin").dt.tz_localize(None)
                except Exception:
                    pass

                dt64 = dt.astype("datetime64[ns]").to_numpy(copy=False)
                self._prebaked_datetimes[inst] = dt64.view("int64")

            print(f"[PREBAKED] Loaded {len(arr)} signals for {inst} from {signal_file}")

        if not self._prebaked_signals:
            print("[PREBAKED] No signals loaded - falling back to inline computation")
            self.config.use_prebaked_signals = False


    def _get_min_data_length(self) -> int:
        min_len = float("inf")

        # Prebaked length
        for inst in getattr(self, "instruments", self.config.instruments):
            if inst in self._prebaked_signals:
                min_len = min(min_len, len(self._prebaked_signals[inst]))

        # Price data length
        if self.data is not None:
            for inst in getattr(self, "instruments", self.config.instruments):
                for _, df in self.data.get(inst, {}).items():
                    min_len = min(min_len, len(df))

        return int(min_len) if min_len != float("inf") else 0

    def _get_simulation_datetime(self, step: Optional[int] = None) -> datetime:
        """
        Get simulation datetime (from prebaked data when available).

        Naive datetimes are interpreted as Europe/Berlin local time.
        """
        if step is None:
            step = self.current_step

        inst = self._obs_instrument

        if inst in self._prebaked_datetimes:
            dt_ns = self._prebaked_datetimes[inst]
            if 0 <= step < len(dt_ns):
                dt = pd.Timestamp(dt_ns[step], unit="ns").to_pydatetime()
                return self._ensure_berlin_aware(dt)

        # Fallback synthetic timeline (15-min bars)
        base = datetime(2020, 1, 1, 9, 0, 0)
        dt = base + timedelta(minutes=int(step) * 15)
        return self._ensure_berlin_aware(dt)

    # ──────────────────────────────────────────────────────────────
    # Price helpers
    # ──────────────────────────────────────────────────────────────
    def _get_df(self, instrument: str) -> Optional[pd.DataFrame]:
        if self.data is None:
            return None
        tf = self.config.primary_timeframe
        if tf in self.data.get(instrument, {}):
            return self.data[instrument][tf]
        available = list(self.data.get(instrument, {}).keys())
        return self.data[instrument][available[0]] if available else None

    def _get_price_at_step(self, instrument: str, step: int) -> float:
        """Get close price at explicit step index."""
        if instrument in self._prebaked_datasets:
            ds = self._prebaked_datasets[instrument]
            idx = min(step, len(ds) - 1)
            prices = ds.get_price(idx)
            return float(prices.get("close", prices.get("open", 0.0)))

        df = self._get_df(instrument)
        if df is None or len(df) == 0:
            return 0.0
        idx = min(step, len(df) - 1)
        return float(df["close"].iloc[idx])

    def _get_price(self, instrument: str) -> float:
        return self._get_price_at_step(instrument, self.current_step)

    def _get_pip_value(self, instrument: str) -> Tuple[float, float]:
        inst = instrument.upper().replace("_", "").replace("/", "")
        if "XAU" in inst or "GOLD" in inst:
            return 100.0, 1.0
        if "XAG" in inst or "SILVER" in inst:
            return 50.0, 1.0
        return 10.0, 10000.0

    def _calculate_pnl(self, position: Position, current_price: float) -> float:
        pip_value, multiplier = self._get_pip_value(position.instrument)
        price_diff = current_price - position.entry_price
        pips = price_diff * multiplier
        if position.direction == "short":
            pips = -pips
        return pips * pip_value * position.lot_size

    def _get_unrealized_pnl_at_step(self, step: int) -> float:
        total = 0.0
        for pos in self.positions.values():
            price = self._get_price_at_step(pos.instrument, step)
            if price > 0:
                total += self._calculate_pnl(pos, price)
        return total

    def _get_unrealized_pnl(self) -> float:
        return self._get_unrealized_pnl_at_step(self.current_step)

    # ──────────────────────────────────────────────────────────────
    # Session / final-exit / weekend rules (training-time)
    # ──────────────────────────────────────────────────────────────
    def _update_day_and_session_counters(self, sim_dt: datetime) -> None:
        # Day reset (daily pnl)
        day_key = self._dt_to_day_key(sim_dt)
        if self._day_key == 0:
            self._day_key = day_key
        elif day_key != self._day_key:
            self._day_key = day_key
            self._daily_pnl = 0.0
            self._day_start_balance = self.balance

        # Session tracking (max trades per session)
        if self._rule_adapter is None:
            self._session_key = -1
            self._trades_in_session = 0
            return

        # Use canonical adapter session key (stable across off-hours and DST semantics)
        try:
            new_session_key = int(self._rule_adapter.session_key(sim_dt))
        except Exception:
            # Fallback: "session starts at no_new_trades_end hour" heuristic
            start_h, _ = self._rule_adapter.session_hours
            if sim_dt.hour < int(start_h):
                from datetime import timedelta
                prev = sim_dt.replace(hour=12, minute=0, second=0, microsecond=0) - timedelta(days=1)
                new_session_key = self._dt_to_day_key(prev)
            else:
                new_session_key = day_key

        if new_session_key != self._session_key:
            self._session_key = new_session_key
            self._trades_in_session = 0


    def _is_final_exit_window(self, sim_dt: datetime, instrument: str) -> bool:
        if self._rule_adapter is None:
            return False
        try:
            return bool(self._rule_adapter.is_hard_close_window(sim_dt, instrument))
        except Exception:
            return False

    def _allow_weekend_holding(self) -> bool:
        if self._rule_adapter is None:
            return True
        try:
            rp = getattr(self._rule_adapter, "_risk_policy", {}) or {}
            prop = rp.get("prop_firm", {}) or {}
            return bool(prop.get("allow_weekend_holding", True))
        except Exception:
            return True

    def _force_flatten_if_needed(self, sim_dt: datetime) -> Optional[str]:
        """
        Force-close positions for:
        - Weekend holding disabled (Fri final exit window, Sat/Sun)
        - Hard close hour (best-effort)
        """
        if not self.positions:
            return None

        if self._rule_adapter is None:
            return None

        hard_close_hour = getattr(self._rule_adapter, "hard_close_hour", 22)

        allow_weekend = self._allow_weekend_holding()
        is_weekend = sim_dt.weekday() >= 5
        is_friday = sim_dt.weekday() == 4

        # If weekend holding is forbidden, close during Friday final-exit window
        if (not allow_weekend) and is_friday and self._is_final_exit_window(sim_dt, self._obs_instrument):
            self._close_all_positions(step_dt=sim_dt)
            return "forced_flatten_weekend_rule"

        # Safety: if data contains weekend bars, flatten immediately
        if (not allow_weekend) and is_weekend:
            self._close_all_positions(step_dt=sim_dt)
            return "forced_flatten_weekend_bar"

        # Hard close hour: flatten at/after hard close
        if sim_dt.hour >= int(hard_close_hour):
            self._close_all_positions(step_dt=sim_dt)
            return "forced_flatten_hard_close"

        return None

    def _close_all_positions(self, step_dt: datetime) -> None:
        """Close all open positions at current prices."""
        closed_pnls: List[float] = []
        for inst, pos in list(self.positions.items()):
            price = self._get_price(inst)
            if price <= 0:
                continue
            pnl = self._calculate_pnl(pos, price)
            self.balance += pnl
            self.total_pnl += pnl
            self._daily_pnl += pnl
            self.trade_count += 1
            self.total_trades += 1
            closed_pnls.append(pnl)
            if pnl > 0:
                self.win_count += 1
                self.winning_trades += 1
            del self.positions[inst]

        # Update prop constraints for each closure (keeps loss-step accurate)
        if self._prop_constraints is not None:
            for pnl in closed_pnls:
                equity = self.balance + self._get_unrealized_pnl()
                self._prop_constraints.update(
                    step_dt=step_dt,
                    equity=equity,
                    current_step=self.episode_step,
                    trade_opened=False,
                    trade_closed_pnl=pnl,
                )

    # ──────────────────────────────────────────────────────────────
    # Gym API
    # ──────────────────────────────────────────────────────────────
    def reset(
        self,
        *,
        seed: Optional[int] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> Tuple[np.ndarray, Dict[str, Any]]:
        super().reset(seed=seed)

        self.balance = self.config.initial_balance
        self.initial_balance = self.config.initial_balance

        self.positions = {}
        self.total_pnl = 0.0
        self.trade_count = 0
        self.win_count = 0

        self.equity = self.config.initial_balance
        self.peak_equity = self.config.initial_balance

        self._daily_pnl = 0.0
        self._day_start_balance = self.config.initial_balance
        self._day_key = 0

        self._session_key = -1
        self._trades_in_session = 0

        # Random start with buffer (safe bounds)
        buffer = 200
        if self._min_data_len <= (buffer + 5):
            self.current_step = 0
        else:
            max_start = self._min_data_len - self.config.max_steps_per_episode - 1
            lo = min(buffer, self._min_data_len - 2)
            hi = max(lo + 1, max_start)
            hi = min(hi, self._min_data_len - 2)
            if hi > lo:
                self.current_step = int(self.np_random.integers(lo, hi))
            else:
                self.current_step = lo

        # Shuffle instrument order occasionally
        if self.np_random.random() < 0.3 and len(self.instruments) > 1:
            self.np_random.shuffle(self.instruments)

        self._obs_instrument = self.instruments[0]
        self.episode_step = 0
        self._episode_actions = []

        # Reset training rules
        if self._prop_constraints is not None:
            start_dt = self._get_simulation_datetime(self.current_step)
            self._prop_constraints.reset(self.config.initial_balance, start_dt)

        if self._safety_filter is not None:
            self._safety_filter.reset()

        sim_dt = self._get_simulation_datetime(self.current_step)
        self._update_day_and_session_counters(sim_dt)

        obs = self._get_observation()
        info = {
            "balance": self.balance,
            "equity": float(self.equity),
            "step": self.current_step,
            "start_position": self.current_step,
            "obs_instrument": self._obs_instrument,
            "simulation_time": str(sim_dt),
        }
        return obs, info

    def step(self, action: np.ndarray) -> Tuple[np.ndarray, float, bool, bool, Dict[str, Any]]:
        # Decision time is CURRENT bar
        sim_dt = self._get_simulation_datetime(self.current_step)
        self._update_day_and_session_counters(sim_dt)

        # Force flatten if needed (final exit / weekend / hard close)
        forced_flatten_reason = self._force_flatten_if_needed(sim_dt)

        # Track action diversity
        if len(action) > 0:
            self._episode_actions.append(float(action[0]))

        # Observation used for filtering at decision time
        obs_for_filter = self._get_observation()

        # Helper: keep PropConstraints authoritative and up-to-date inside the same step loop
        def _pc_update(trade_opened: bool = False, trade_closed_pnl: Optional[float] = None) -> None:
            if self._prop_constraints is None:
                return
            equity_now = float(self.balance + self._get_unrealized_pnl_at_step(self.current_step))
            self._prop_constraints.update(
                step_dt=sim_dt,
                equity=equity_now,
                current_step=self.episode_step,
                trade_opened=bool(trade_opened),
                trade_closed_pnl=(float(trade_closed_pnl) if trade_closed_pnl is not None else None),
            )

        # Parse action for each instrument
        for i, inst in enumerate(self.instruments):
            if i * 2 + 1 >= len(action):
                break

            direction_score = float(action[i * 2])
            size_score = float(action[i * 2 + 1])

            # Base parse (before safety filter)
            if direction_score > self.config.direction_long_threshold:
                desired_dir = "long"
            elif direction_score < self.config.direction_short_threshold:
                desired_dir = "short"
            else:
                desired_dir = "flat"

            raw_size = float(np.clip((size_score + 1.0) / 2.0, 0.0, 1.0))

            # If forced flatten, override all desired entries (but still allow closes via logic below)
            in_final_exit = self._is_final_exit_window(sim_dt, inst)
            block_new_entries_by_window = bool(in_final_exit)

            # Apply SafetyFilter (for NEW ENTRIES and reversals-as-new-entries)
            filtered_dir = desired_dir
            filtered_size = raw_size
            blocked_reasons: List[str] = []

            def run_filter_for_entry() -> Tuple[str, float, List[str]]:
                if self._safety_filter is None:
                    return desired_dir, raw_size, []
                fa = self._safety_filter.filter_action(
                    direction_score=direction_score,
                    size_score=size_score,
                    obs=obs_for_filter,
                    current_dt=sim_dt,
                    current_step=self.episode_step,
                    instrument=inst,
                    current_positions=len(self.positions),
                    has_position_in_instrument=(inst in self.positions),
                )
                if fa.direction == 1:
                    d = "long"
                elif fa.direction == -1:
                    d = "short"
                else:
                    d = "flat"
                return d, float(fa.size_mult), list(fa.reasons)

            # For existing positions: decide close/reverse (closing allowed even if entry-blocked)
            current_price = self._get_price(inst)
            if current_price <= 0:
                continue

            if inst in self.positions:
                pos = self.positions[inst]
                pnl = self._calculate_pnl(pos, current_price)
                pos.peak_pnl = max(pos.peak_pnl, pnl)

                position_age = self.episode_step - pos.entry_step

                should_close = False
                if desired_dir == "flat" or desired_dir != pos.direction:
                    should_close = True
                elif position_age > self.config.max_position_age:
                    should_close = True
                elif pnl >= self.config.take_profit_eur:
                    should_close = True
                elif pnl <= -self.config.stop_loss_eur:
                    should_close = True
                elif pos.peak_pnl > 100 and pnl < pos.peak_pnl * 0.5:
                    should_close = True

                if should_close:
                    self.balance += pnl
                    self.total_pnl += pnl
                    self._daily_pnl += pnl
                    self.trade_count += 1
                    self.total_trades += 1
                    if pnl > 0:
                        self.win_count += 1
                        self.winning_trades += 1
                    del self.positions[inst]

                    # PropConstraints: close event (keeps loss-step timing accurate)
                    _pc_update(trade_opened=False, trade_closed_pnl=float(pnl))

                # Reversal is a NEW ENTRY after close -> filter as new entry
                if desired_dir in ("long", "short") and (desired_dir != pos.direction):
                    filtered_dir, filtered_size, blocked_reasons = run_filter_for_entry()
                else:
                    filtered_dir, filtered_size, blocked_reasons = desired_dir, raw_size, []

            else:
                # No existing position: pure new entry
                filtered_dir, filtered_size, blocked_reasons = run_filter_for_entry()

            # Defensive: if SafetyFilter is disabled, still block weekend entries when weekend holding is disallowed
            if self._safety_filter is None and self._rule_adapter is not None and filtered_dir in ("long", "short"):
                try:
                    if self._rule_adapter.should_flatten_for_weekend(sim_dt, inst):
                        filtered_dir = "flat"
                        blocked_reasons.append("weekend_blocked")
                except Exception:
                    pass

            # Enforce session filter toggle (new entries only)
            if filtered_dir in ("long", "short") and self._rule_adapter is not None:
                if self.config.enable_session_filter:
                    if not self._rule_adapter.is_trading_session_allowed(sim_dt, inst):
                        filtered_dir = "flat"
                        blocked_reasons.append("session_blocked")

                # Final-exit window blocks new entries (close/defend handled above)
                if block_new_entries_by_window:
                    filtered_dir = "flat"
                    blocked_reasons.append("final_exit_window")

            # Enforce max trades per session (new entries only)
            if filtered_dir in ("long", "short") and self._rule_adapter is not None:
                try:
                    limit = int(self._rule_adapter.get_max_trades_per_session(inst))
                except Exception:
                    limit = 10
                if self._trades_in_session >= limit:
                    filtered_dir = "flat"
                    blocked_reasons.append("max_trades_per_session_exceeded")

            # Lot sizing
            lot_size = self.config.base_lot_size + filtered_size * (self.config.max_lot_size - self.config.base_lot_size)
            lot_size = float(max(0.01, min(self.config.max_lot_size, lot_size)))

            # Open new position (only if allowed)
            if inst not in self.positions and filtered_dir in ("long", "short"):
                if self.balance > self.config.initial_balance * 0.5:
                    self.positions[inst] = Position(
                        instrument=inst,
                        direction=filtered_dir,
                        entry_price=current_price,
                        entry_step=self.episode_step,
                        lot_size=lot_size,
                    )
                    self._trades_in_session += 1

                    # PropConstraints: open event (authoritative for trade/session caps)
                    _pc_update(trade_opened=True, trade_closed_pnl=None)

        # Update equity/peaks after decisions at this bar
        self.equity = self.balance + self._get_unrealized_pnl_at_step(self.current_step)
        self.peak_equity = max(self.peak_equity, self.equity)

        # Always update once per step for drawdown tracking consistency
        _pc_update(trade_opened=False, trade_closed_pnl=None)

        reward = self._calculate_reward()

        # Termination logic (equity-based drawdown)
        terminated = False
        truncated = False
        termination_reason = ""

        drawdown = (self.peak_equity - self.equity) / max(self.peak_equity, 1.0)
        if drawdown >= self.config.max_drawdown_pct:
            terminated = True
            termination_reason = "max_drawdown"
        if self.equity <= 0:
            terminated = True
            termination_reason = "bankrupt"

        # Prop constraint termination (serious violations)
        if self._prop_constraints is not None and self._safety_filter is not None:
            should_term, term_reason = self._safety_filter.should_terminate()
            if should_term:
                terminated = True
                termination_reason = term_reason

        # Advance to next bar (avoids look-ahead bias)
        next_step = self.current_step + 1
        next_episode_step = self.episode_step + 1

        if next_episode_step >= self.config.max_steps_per_episode:
            truncated = True
            termination_reason = termination_reason or "max_steps"
        if self._min_data_len > 0 and next_step >= self._min_data_len:
            truncated = True
            termination_reason = termination_reason or "data_end"

        self.current_step = min(next_step, max(self._min_data_len - 1, 0)) if self._min_data_len > 0 else next_step
        self.episode_step = next_episode_step

        obs = self._get_observation()

        action_diversity = 0.0
        if len(self._episode_actions) > 10:
            actions = np.array(self._episode_actions, dtype=np.float32)
            action_diversity = float(np.std(actions))

        info: Dict[str, Any] = {
            "balance": float(self.balance),
            "equity": float(self.equity),
            "drawdown": float(drawdown),
            "total_pnl": float(self.total_pnl),
            "daily_pnl": float(self._daily_pnl),
            "trade_count": int(self.trade_count),
            "win_rate": float(self.win_count / max(self.trade_count, 1)),
            "open_positions": int(len(self.positions)),
            "step": int(self.current_step),
            "episode_step": int(self.episode_step),
            "action_diversity": float(action_diversity),
            "obs_instrument": self._obs_instrument,
            "simulation_time": str(sim_dt),
            "trades_in_session": int(self._trades_in_session),
        }

        if forced_flatten_reason:
            info["forced_flatten"] = forced_flatten_reason

        # Prop constraint telemetry
        if self._prop_constraints is not None:
            v = self._prop_constraints.violations()
            info.update({
                "daily_dd": float(v.get("daily_dd_magnitude", 0.0)),
                "total_dd": float(v.get("total_dd_magnitude", 0.0)),
                "trades_today": int(v.get("trades_today", 0)),
                "prop_dd_margin": float(v.get("total_dd_margin", 0.0)),
                "consecutive_losses": int(v.get("consecutive_losses", 0)),
                "session_key": int(v.get("session_key", self._session_key)),
                "trades_this_session": int(v.get("trades_this_session", 0)),
            })

        if self._rule_adapter is not None:
            try:
                info["max_trades_per_session"] = int(self._rule_adapter.get_max_trades_per_session(self._obs_instrument))
            except Exception:
                info["max_trades_per_session"] = 10

        if termination_reason:
            info["termination_reason"] = termination_reason

        return obs, float(reward), bool(terminated), bool(truncated), info


    # ──────────────────────────────────────────────────────────────
    # Reward shaping
    # ──────────────────────────────────────────────────────────────
    def _calculate_reward(self) -> float:
        pnl_change = self.balance - getattr(self, "_last_balance", self.balance)
        base_reward = pnl_change / max(self.config.initial_balance, 1.0) * 100.0

        shape_bonus = 0.0
        shape_penalty = 0.0

        obs = self._get_observation()
        if obs is not None and obs.shape[0] == 64:
            consensus_dir = float(obs[OBS_IDX["consensus_direction"]])
            consensus_conf = float(obs[OBS_IDX["consensus_confidence"]])
            momentum = float(obs[OBS_IDX["m15_momentum"]])
            volatility = float(obs[OBS_IDX["m15_volatility"]])
            htf_alignment = float(obs[OBS_IDX["htf_alignment"]])
            timing_score = float(obs[OBS_IDX["timing_score"]])

            for inst, pos in self.positions.items():
                pos_dir = 1.0 if pos.direction == "long" else -1.0
                pos_age = self.episode_step - pos.entry_step

                with_trend = (pos_dir * consensus_dir) > 0.0
                fresh_momentum = abs(momentum) < 0.7
                good_timing = timing_score > 0.4

                if pos_age <= 2:
                    if with_trend and good_timing and consensus_conf > 0.6:
                        shape_bonus += 0.03
                    elif with_trend and good_timing:
                        shape_bonus += 0.02
                    elif with_trend and fresh_momentum:
                        shape_bonus += 0.01
                    elif abs(momentum) > 0.8 and (pos_dir * momentum) > 0:
                        shape_penalty += 0.02

                current_pnl = self._calculate_pnl(pos, self._get_price(inst))
                pos.peak_pnl = max(pos.peak_pnl, current_pnl)

                pnl_to_tp = current_pnl / max(self.config.take_profit_eur, 1.0)
                if pos_age < 20 and pnl_to_tp > 0.5:
                    shape_bonus += 0.01
                if pos_age > 30 and current_pnl < 0:
                    shape_penalty += 0.005 * (pos_age - 30) / 10.0
                if pos.peak_pnl > 0 and current_pnl < pos.peak_pnl * 0.5:
                    shape_penalty += 0.01

            if self.positions:
                if -0.5 < volatility < 0.5:
                    shape_bonus += 0.005
                elif volatility > 0.8:
                    shape_penalty += 0.01

            if not self.positions:
                if abs(htf_alignment) < 0.2 and abs(momentum) < 0.2:
                    shape_bonus += 0.002
                if volatility > 0.8:
                    shape_bonus += 0.002

        drawdown = (self.peak_equity - self.equity) / max(self.peak_equity, 1.0)
        risk_penalty = float(drawdown) * 0.15

        overtrade_penalty = 0.0
        if self.trade_count > 8:
            overtrade_penalty = 0.015 * (self.trade_count - 8)

        consistency_bonus = 0.0
        if self.trade_count >= 3:
            win_rate = self.win_count / self.trade_count
            if win_rate > 0.6:
                consistency_bonus = (win_rate - 0.5) * 0.05
            elif win_rate < 0.4:
                shape_penalty += 0.01

        reward = base_reward + shape_bonus - shape_penalty - risk_penalty - overtrade_penalty + consistency_bonus
        self._last_balance = self.balance
        return float(np.clip(reward, -2.0, 2.0))

    # ──────────────────────────────────────────────────────────────
    # Observation building
    # ──────────────────────────────────────────────────────────────
    def _get_observation(self) -> np.ndarray:
        """
        Build the canonical 64-dim observation.

        PREBAKED mode:
          - start from module-generated row
          - overwrite account state [40..47] live

        INLINE mode:
          - compute lightweight approximations aligned to the canonical layout
        """
        # ── PREBAKED ───────────────────────────────────────────────
        if self.config.use_prebaked_signals:
            inst = self._obs_instrument
            signals = self._prebaked_signals.get(inst)
            if signals is not None and 0 <= self.current_step < len(signals):
                obs = signals[self.current_step].copy()

                unreal = self._get_unrealized_pnl()
                self.equity = self.balance + unreal
                self.peak_equity = max(self.peak_equity, self.equity)
                drawdown = (self.peak_equity - self.equity) / max(self.peak_equity, 1.0)

                obs[OBS_IDX["balance_norm"]] = self.balance / max(self.config.initial_balance, 1.0) - 1.0
                obs[OBS_IDX["equity_norm"]] = self.equity / max(self.config.initial_balance, 1.0) - 1.0
                obs[OBS_IDX["margin_used"]] = float(min(1.0, len(self.positions) / 4.0))
                obs[OBS_IDX["drawdown_pct"]] = float(drawdown)
                obs[OBS_IDX["position_count"]] = float(min(1.0, len(self.positions) / 4.0))

                total_exposure = sum(
                    abs(self._calculate_pnl(pos, self._get_price(pos.instrument)))
                    for pos in self.positions.values()
                )
                obs[OBS_IDX["position_exposure"]] = float(total_exposure / max(self.config.initial_balance, 1.0))
                obs[OBS_IDX["daily_pnl_norm"]] = float(self._daily_pnl / max(self.config.initial_balance, 1.0))
                obs[OBS_IDX["win_rate"]] = float(self.win_count / max(self.trade_count, 1))

                return np.nan_to_num(obs, nan=0.0, posinf=1.0, neginf=-1.0).astype(np.float32)

        # ── INLINE (approximate) ───────────────────────────────────
        obs = np.zeros(64, dtype=np.float32)

        inst = self._obs_instrument
        df = self._get_df(inst)
        if df is None or len(df) < 60:
            return obs

        idx = min(self.current_step, len(df) - 1)

        lookback = 60
        start = max(0, idx - lookback)
        closes = df["close"].iloc[start:idx + 1].to_numpy(dtype=np.float32, copy=False)
        highs = df["high"].iloc[start:idx + 1].to_numpy(dtype=np.float32, copy=False) if "high" in df.columns else closes
        lows = df["low"].iloc[start:idx + 1].to_numpy(dtype=np.float32, copy=False) if "low" in df.columns else closes
        vols = df["volume"].iloc[start:idx + 1].to_numpy(dtype=np.float32, copy=False) if "volume" in df.columns else None

        close = float(closes[-1])
        prev = float(closes[-2]) if len(closes) >= 2 else close

        sma50 = float(np.mean(closes[-50:])) if len(closes) >= 50 else float(np.mean(closes))
        obs[OBS_IDX["m15_price_norm"]] = float(close / max(sma50, 1e-8) - 1.0)

        def ret(n: int) -> float:
            if len(closes) > n:
                a = float(closes[-1])
                b = float(closes[-1 - n])
                return (a - b) / max(abs(b), 1e-8)
            return 0.0

        obs[OBS_IDX["m15_return_1"]] = float(np.clip((close - prev) / max(abs(prev), 1e-8), -0.05, 0.05))
        obs[OBS_IDX["m15_return_5"]] = float(np.clip(ret(5), -0.10, 0.10))
        obs[OBS_IDX["m15_return_20"]] = float(np.clip(ret(20), -0.20, 0.20))

        rets = np.diff(closes) / np.maximum(closes[:-1], 1e-8) if len(closes) >= 3 else np.array([0.0], dtype=np.float32)
        vol20 = float(np.std(rets[-20:])) if len(rets) >= 20 else float(np.std(rets))
        obs[OBS_IDX["m15_volatility"]] = float(np.clip(vol20 * 100.0, 0.0, 2.0))

        if len(closes) >= 15:
            ch = np.diff(closes[-15:])
            gains = float(np.sum(ch[ch > 0]))
            losses = float(-np.sum(ch[ch < 0]))
            rsi = gains / max(gains + losses, 1e-8)
            obs[OBS_IDX["m15_rsi"]] = float(rsi * 2.0 - 1.0)

        if len(closes) >= 15:
            tr = np.maximum(highs[-15:], closes[-15:]) - np.minimum(lows[-15:], closes[-15:])
            atr = float(np.mean(tr))
            obs[OBS_IDX["m15_atr_norm"]] = float(np.clip(atr / max(close, 1e-8), 0.0, 0.05))

        sma20 = float(np.mean(closes[-20:])) if len(closes) >= 20 else float(np.mean(closes))
        trend_strength = (sma20 - sma50) / max(abs(sma50), 1e-8)
        obs[OBS_IDX["m15_trend_strength"]] = float(np.clip(trend_strength * 10.0, -1.0, 1.0))

        mom = ret(10)
        obs[OBS_IDX["m15_momentum"]] = float(np.clip(mom * 10.0, -1.0, 1.0))

        if vols is not None and len(vols) >= 21:
            v = float(vols[-1])
            av = float(np.mean(vols[-20:]))
            obs[OBS_IDX["m15_volume_ratio"]] = float(np.clip(v / max(av, 1e-8) - 1.0, -2.0, 2.0))

        h1_trend = float(np.clip(trend_strength * 10.0, -1.0, 1.0))
        h4_trend = h1_trend * 0.8
        d1_trend = h1_trend * 0.6
        obs[OBS_IDX["htf_h1_trend"]] = h1_trend
        obs[OBS_IDX["htf_h4_trend"]] = h4_trend
        obs[OBS_IDX["htf_d1_trend"]] = d1_trend

        signs = np.array([np.sign(h1_trend), np.sign(h4_trend), np.sign(d1_trend)], dtype=np.float32)
        alignment = float(np.mean(signs))
        obs[OBS_IDX["htf_alignment"]] = alignment
        obs[OBS_IDX["htf_volatility_ratio"]] = 1.0
        obs[OBS_IDX["htf_context_strength"]] = float(np.clip(abs(alignment), 0.0, 1.0))

        obs[OBS_IDX["expert_theme_signal"]] = obs[OBS_IDX["htf_alignment"]]
        obs[OBS_IDX["expert_trend_signal"]] = obs[OBS_IDX["m15_trend_strength"]]
        obs[OBS_IDX["expert_momentum_signal"]] = obs[OBS_IDX["m15_momentum"]]

        if "datetime" in df.columns:
            try:
                dt = pd.to_datetime(df["datetime"].iloc[idx])
                hour = float(getattr(dt, "hour", 0))
                obs[OBS_IDX["expert_seasonality_signal"]] = float(np.sin(2.0 * np.pi * hour / 24.0))
            except Exception:
                pass

        experts = np.array([
            obs[OBS_IDX["expert_theme_signal"]],
            obs[OBS_IDX["expert_trend_signal"]],
            obs[OBS_IDX["expert_momentum_signal"]],
            obs[OBS_IDX["expert_seasonality_signal"]],
        ], dtype=np.float32)
        cd = float(np.clip(np.mean(experts), -1.0, 1.0))
        conf = float(np.clip(abs(cd), 0.0, 1.0))
        agree = float(np.clip(1.0 - float(np.std(experts)), 0.0, 1.0))

        obs[OBS_IDX["consensus_direction"]] = cd
        obs[OBS_IDX["consensus_confidence"]] = conf
        obs[OBS_IDX["consensus_agreement"]] = agree

        bullish = int(np.sum(experts > 0.1))
        bearish = int(np.sum(experts < -0.1))
        neutral = int(len(experts) - bullish - bearish)
        obs[OBS_IDX["committee_bullish_count"]] = float(bullish) / 4.0
        obs[OBS_IDX["committee_bearish_count"]] = float(bearish) / 4.0
        obs[OBS_IDX["committee_neutral_count"]] = float(neutral) / 4.0
        obs[OBS_IDX["committee_strength"]] = conf
        obs[OBS_IDX["committee_clarity"]] = agree

        unreal = self._get_unrealized_pnl()
        self.equity = self.balance + unreal
        self.peak_equity = max(self.peak_equity, self.equity)
        dd = (self.peak_equity - self.equity) / max(self.peak_equity, 1.0)

        exposure = 0.0
        for pos in self.positions.values():
            exposure += abs(self._calculate_pnl(pos, self._get_price(pos.instrument)))

        risk_level = float(np.clip(dd + obs[OBS_IDX["m15_volatility"]] * 0.2, 0.0, 1.0))
        obs[OBS_IDX["risk_level"]] = risk_level
        obs[OBS_IDX["risk_gate"]] = 1.0 if dd < self.config.max_drawdown_pct else 0.0
        obs[OBS_IDX["memory_gate"]] = 1.0
        obs[OBS_IDX["danger_zone_count"]] = float(len(self.positions)) / 4.0
        obs[OBS_IDX["recent_loss_streak"]] = 0.0
        obs[OBS_IDX["drawdown_risk"]] = float(dd)
        obs[OBS_IDX["exposure_risk"]] = float(exposure / max(self.config.initial_balance, 1.0))
        obs[OBS_IDX["risk_adjusted_size"]] = float(1.0 - risk_level)

        obs[OBS_IDX["balance_norm"]] = self.balance / max(self.config.initial_balance, 1.0) - 1.0
        obs[OBS_IDX["equity_norm"]] = self.equity / max(self.config.initial_balance, 1.0) - 1.0
        obs[OBS_IDX["margin_used"]] = float(min(1.0, len(self.positions) / 4.0))
        obs[OBS_IDX["drawdown_pct"]] = float(dd)
        obs[OBS_IDX["position_count"]] = float(min(1.0, len(self.positions) / 4.0))
        obs[OBS_IDX["position_exposure"]] = float(exposure / max(self.config.initial_balance, 1.0))
        obs[OBS_IDX["daily_pnl_norm"]] = float(self._daily_pnl / max(self.config.initial_balance, 1.0))
        obs[OBS_IDX["win_rate"]] = float(self.win_count / max(self.trade_count, 1))

        if len(closes) >= 20:
            x = np.arange(len(closes[-20:]), dtype=np.float32)
            y = closes[-20:]
            slope = float(np.polyfit(x, y, 1)[0])
            pred_ret = slope / max(abs(close), 1e-8)

            obs[OBS_IDX["wm_price_pred"]] = float(np.clip(pred_ret * 1000.0, -1.0, 1.0))
            obs[OBS_IDX["wm_volatility_pred"]] = float(np.clip(vol20 * 100.0, 0.0, 1.0))
            obs[OBS_IDX["wm_trend_pred"]] = float(np.clip(slope * 10000.0, -1.0, 1.0))
            obs[OBS_IDX["wm_confidence"]] = float(np.clip(1.0 - vol20 * 20.0, 0.0, 1.0))

            bull = max(0.0, obs[OBS_IDX["wm_trend_pred"]])
            bear = max(0.0, -obs[OBS_IDX["wm_trend_pred"]])
            rng = float(np.clip(1.0 - (bull + bear), 0.0, 1.0))
            obs[OBS_IDX["wm_scenario_bull"]] = float(np.clip(bull, 0.0, 1.0))
            obs[OBS_IDX["wm_scenario_bear"]] = float(np.clip(bear, 0.0, 1.0))
            obs[OBS_IDX["wm_scenario_range"]] = rng
            obs[OBS_IDX["wm_uncertainty"]] = float(np.clip(vol20 * 50.0, 0.0, 1.0))

        obs[OBS_IDX["mode_intensity"]] = float(np.clip(obs[OBS_IDX["m15_volatility"]], 0.0, 1.0))
        obs[OBS_IDX["mode_entry_allowed"]] = 1.0
        obs[OBS_IDX["mode_entry_quality"]] = float(np.clip(obs[OBS_IDX["consensus_confidence"]], 0.0, 1.0))
        obs[OBS_IDX["mode_risk_mult"]] = float(np.clip(1.0 - risk_level, 0.0, 1.0))

        obs[OBS_IDX["timing_score"]] = float(np.clip(
            obs[OBS_IDX["consensus_confidence"]] * obs[OBS_IDX["htf_context_strength"]],
            0.0, 1.0
        ))

        session_quality = 0.5
        if "datetime" in df.columns:
            try:
                dt = pd.to_datetime(df["datetime"].iloc[idx])
                h = int(getattr(dt, "hour", 0))
                if 13 <= h <= 16:
                    session_quality = 1.0
                elif 7 <= h <= 11 or 17 <= h <= 20:
                    session_quality = 0.7
                else:
                    session_quality = 0.4
            except Exception:
                pass

        obs[OBS_IDX["session_quality"]] = float(session_quality)
        obs[OBS_IDX["liquidity_score"]] = float(np.clip(0.5 + 0.5 * session_quality, 0.0, 1.0))
        obs[OBS_IDX["mode_effectiveness"]] = float(np.clip(
            0.5 + 0.5 * (self.total_pnl / max(self.config.initial_balance, 1.0)),
            0.0, 1.0
        ))

        return np.nan_to_num(obs, nan=0.0, posinf=1.0, neginf=-1.0).astype(np.float32)

    # ──────────────────────────────────────────────────────────────
    # Render/close
    # ──────────────────────────────────────────────────────────────
    def render(self, mode: str = "human") -> None:
        print(
            f"Step {self.episode_step}: Balance={self.balance:.2f}, "
            f"Equity={self.equity:.2f}, PnL={self.total_pnl:.2f}, Positions={len(self.positions)}"
        )

    def close(self) -> None:
        pass
